# About
module: [MODULE NAME]
author: Shortcut
author_url: https://www.shortcut.io
readme: README.md
copyright: '© All rights reserved 2022 Shortcut Scandinavia Apps AB'

# URLs
github_url: https://github.com/shortcut/shortcut-foundation-ios
root_url: https://www.shortcut.io
github_file_prefix: https://github.com/shortcut/shortcut-foundation-ios/blob/master

# Generation
clean: true
output: Docs
clean: true
min_acl: public
hide_documentation_coverage: false
skip_undocumented: true
